name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            nolabelregistry/nolabel-frontend:latest
            nolabelregistry/nolabel-frontend:${{ github.sha }}

  trigger-argocd:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Argo CD
        run: curl -X POST ${{ secrets.ARGOCD_WEBHOOK_URL }}
